name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # This will use the latest Node.js 18.x.x version available

      - name: Verify Node.js Version
        run: node -v  # Check the Node.js version to ensure it's correctly set

      - name: Install dependencies
        run: npm install --force  # Using --force to bypass peer dependency conflicts

      - name: Build the project
        run: npm run build  # Adjust if your build command is different

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_PEBBLE_04D579010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions, you do not need to create your own token
          action: "upload"
          app_location: "/"  # Adjust if different
          api_location: ""
          output_location: "dist/my-app"  # Adjust based on your Angular output configuration

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_PEBBLE_04D579010 }}
          action: "close"
